version: 0.{build}

pull_requests:
  do_not_increment_build_number: true
 
image: Visual Studio 2017
platform: x86
configuration: Release

cache:
- C:\DreamcastConversion\system
- C:\DreamcastConversion\textures

clone_folder: c:\projects\sadx_dreamcast

init:
- ps: mkdir C:\DreamcastConversion
- ps: Set-Content -Value "Name=Dreamcast Conversion`r`nDescription=Brings back levels, textures, object models, special effects, branding etc. from the Dreamcast version of SA1.  Fixes various SADX bugs.`r`nAuthor=PkR`r`nVersion=$env:APPVEYOR_BUILD_VERSION`r`nDLLFile=DCMods_Main.dll`r`nUpdateUrl=http://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/DreamcastConversion/`r`nChangelogUrl=http://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Changelog.txt" -Path C:\DreamcastConversion\mod.ini
- cmd: cinst wget
- cmd: cd \
- cmd: wget -np --no-parent -nH --cut-dirs 4 -N "https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Various/mod-manifest-gen.exe"
- cmd: wget -r -np --no-parent -nH --cut-dirs 4 -N --reject htm,html,tmp "https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/DreamcastConversion/system/"
- cmd: wget -r -np --no-parent -nH --cut-dirs 4 -N --reject htm,html,tmp "https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/DreamcastConversion/textures/"

install:
- cmd: cd C:\projects\sadx_dreamcast
- cmd: git submodule update --init --recursive

build:
  project: DCMods_Main.sln
  
after_build:
- cmd: copy C:\projects\sadx_dreamcast\Release\DCMods_Main.dll C:\DreamcastConversion\DCMods_Main.dll
- ps: $MyProcess = Start-Process "C:\mod-manifest-gen.exe C:\DreamcastConversion" -PassThru
- cmd: cd C:\DreamcastConversion
- cmd: dir

on_finish:
- ps: Stop-Process -Id $MyProcess.Id
