version: 0.{build}

pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2017
platform: x86
configuration: Release
clone_depth: 1

cache:
- C:\DreamcastConversion\system
- C:\DreamcastConversion\textures

init:
- ps: mkdir C:\DreamcastConversion
- ps: Set-Content -Value "Name=Dreamcast Conversion`r`nDescription=Brings back levels, textures, object models, special effects, branding etc. from the Dreamcast version of SA1.  Fixes various SADX bugs.`r`nAuthor=PkR`r`nVersion=$env:APPVEYOR_BUILD_VERSION`r`nDLLFile=DCMods_Main.dll`r`nUpdateUrl=http://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/DreamcastConversion/`r`nChangelogUrl=http://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Changelog.txt" -Path C:\DreamcastConversion\mod.ini
- cmd: cd \
- cmd: cd C:\projects\sadx-dreamcast
- cmd: git init

before_build:
- cmd: git submodule update --init --recursive

build:
  project: DCMods_Main.sln
  
after_build:
- cmd: copy C:\projects\sadx_dreamcast\Release\DCMods_Main.dll C:\DreamcastConversion\DCMods_Main.dll
- ps: $MyProcess = Start-Process "C:\mod-manifest-gen.exe C:\DreamcastConversion" -PassThru
- cmd: cd C:\DreamcastConversion
- cmd: dir
